spring:
  datasource:
    url: jdbc:mysql://localhost:3306/to_do_app_java?useUnicode=true&characterEncoding=UTF-8&connectionTimeZone=SERVER
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
